### ISSUE TITLE
A copy question

### ISSUE THREAD

**Issue by pftbest** [psiphi75/mpu9250-i2c#2]
Hello

```
pub fn copy(cal: &Self) -> Self {
```

I'm curious why do you create a custom copy function when the default derive(Clone) implementation works the same?
Is there some hidden difference that I'm not noticing?

**Comment by psiphi75** [comment]
That's a good question.  I haven't looked at the code responsible and I can't remember why I did this.  If you are looking for a well maintained mpu9250 i2c driver you should check out this: https://crates.io/crates/mpu9250.  I wrote this because at the time there were no other Rust crates with i2c MPU9250 support and my Rust skills at the time were not good enough to contribute to the other crate.
